import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/NunitoSans-VariableFont.woff2',
  variable: '--font-nunito-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/PressStart2P-Regular.woff',
  variable: '--font-geist-mono',
  weight: '400',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
